Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserNotepad.Models;
using ClosedXML.Excel;
using System.Data;

namespace UserNotepad.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly Context.AppContext _context;
        
        public StatisticsController(Context.AppContext context){
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Export()
        {
            DataTable dt = new("Grid");
            dt.Columns.AddRange(
                new DataColumn[6] { 
                    new("Name"),
                    new("Surname"),
                    new("Title"),
                    new("Gender"),
                    new("Birth Date"),
                    new("Age") 
                }
            );
            List<User> users = await _context.Users.ToListAsync();
            foreach (var user in users)
            {
                dt.Rows.Add(user.Name, user.Surname, GiveUserTitle(user.Gender), user.Gender, user.BirthDate, GiveUserAge(user.BirthDate));
            }

            using XLWorkbook wb = new();
            wb.Worksheets.Add(dt);
            using MemoryStream stream = new();
            wb.SaveAs(stream);
            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", DateTime.Now.ToString()+".xlsx");
        }

        private string GiveUserTitle(string? userGender){
            if(userGender == null){
                return "null";
            }
            var userGenderUppercase = userGender.ToUpper();
            if(userGenderUppercase.Equals("FEMALE")){
                return "Pani";
            }
            if(userGenderUppercase.Equals("MALE")){
                return "Pan";
            }
            return "Pax";
        }
        private int GiveUserAge(DateOnly birthDate){
            int age = DateTime.Now.Year - birthDate.Year;
            if (birthDate > DateOnly.FromDateTime(DateTime.Now.AddYears(-age))) 
                age--;
            return age;
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserNotepad.Models;
using UserNotepad.DTOs;

namespace UserNotepad.Controllers
{
    public class UserController : Controller
    {
        private readonly Context.AppContext _context;
        
        public UserController(Context.AppContext context){
            _context = context;
        }

        public async Task<IActionResult> ListUsers()
        {
            List<User> users = await _context.Users.ToListAsync();
            ViewData["users"] = users;
            return View(users);
        }
        [HttpGet]
        public IActionResult CreateNewUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNewUser(UserDTO userDTO)
        {
            var user = new User(userDTO);
            if(user.BirthDate <= DateOnly.FromDateTime(DateTime.Today)){
                _context.Users.Add(user);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("ListUsers");
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser(int? id, UserDTO userDTO)
        {
            var user = await _context.Users.FindAsync(id);
            if(user == null)
            {
                return NotFound();
            }
            user.UpdateUserData(userDTO);
            _context.Update(user);
            await _context.SaveChangesAsync();
            return View(user);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteUser(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("DeleteUser")]
        public async Task<IActionResult> DeleteUser(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var extras = await _context.ExtraDatas.Where(e => e.UserId == id).ToListAsync();
            _context.ExtraDatas.RemoveRange(extras);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListUsers");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserNotepad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserNotepad.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UserNotepad</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="ListUsers">User List</a>
                        </li>
                        <li class="nav-item">
                            <form asp-controller="Statistics" asp-action="Export" method="POST">
                                <input type="submit" value="Export Data" class="btn btn-primary"/>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UserNotepad
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>