Models/User.cs
using System.ComponentModel.DataAnnotations;
using UserNotepad.DTOs;

namespace UserNotepad.Models;

public class User
{
    public int Id {get; set;}
    [Required]
    [StringLength(50)]
    [RegularExpression(@"^[A-Z]+[a-z]*$")]
    public string? Name {get; set;}
    [Required]
    [StringLength(150)]
    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
    public string? Surname {get; set;}
    [Required]
    [DisplayFormat( DataFormatString = "{0:dd.MM.yyyy}")]
    [Display(Name = "Birth Date")]
    [DateValidation(ErrorMessage = "Date is invalid")]
    public DateOnly BirthDate {get; set;}
    [Required]
    public string? Gender {get; set;}

    public User(){}
    public User(UserDTO transfer){
        Name = transfer.Name;
        Surname = transfer.Surname;
        Gender = transfer.Gender;
        if(transfer.BirthDate != null)
        BirthDate = DateOnly.Parse(transfer.BirthDate);
    }
    public void UpdateUserData(UserDTO transfer){
        Name = transfer.Name;
        Surname = transfer.Surname;
        Gender = transfer.Gender;
        if(transfer.BirthDate != null)
        BirthDate = DateOnly.Parse(transfer.BirthDate);
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserNotepad.Models;
using UserNotepad.DTOs;

namespace UserNotepad.Controllers
{
    public class UserController : Controller
    {
        private readonly Context.AppContext _context;
        
        public UserController(Context.AppContext context){
            _context = context;
        }

        public async Task<IActionResult> ListUsers()
        {
            List<User> users = await _context.Users.ToListAsync();
            ViewData["users"] = users;
            return View(users);
        }
        [HttpGet]
        public IActionResult CreateNewUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNewUser(UserDTO userDTO)
        {
            var user = new User(userDTO);
            if(user.BirthDate <= DateOnly.FromDateTime(DateTime.Today)){
                _context.Users.Add(user);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("ListUsers");
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser(int? id, UserDTO userDTO)
        {
            var user = await _context.Users.FindAsync(id);
            if(user == null)
            {
                return NotFound();
            }
            user.UpdateUserData(userDTO);
            _context.Update(user);
            await _context.SaveChangesAsync();
            return View(user);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteUser(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("DeleteUser")]
        public async Task<IActionResult> DeleteUser(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var extras = await _context.ExtraDatas.Where(e => e.UserId == id).ToListAsync();
            _context.ExtraDatas.RemoveRange(extras);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListUsers");
        }
    }
}

Controllers/UserExtrasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserNotepad.Models;
using UserNotepad.DTOs;

namespace UserNotepad.Controllers;
public class UserExtrasController : Controller
{
    private readonly Context.AppContext _context;
    
    public UserExtrasController(Context.AppContext context){
        _context = context;
    }
    
    public async Task<IActionResult> Details(int? id){
        var user = await _context.Users.FindAsync(id);
        if(user == null)
        {
            return NotFound();
        }
        var extras = await _context.ExtraDatas.Where(d=> d.UserId == id).ToListAsync();
        ExtraDataViewModel transfer = new(user, extras);
        return View(transfer);
    }
    [HttpPost]
    public async Task<IActionResult> CreateExtra(ExtraDTO extraDTO){
        var user = await _context.Users.FindAsync(extraDTO.UserId);
        if(user == null)
        {
            return NotFound();
        }
        ExtraData extraData = new(extraDTO);
        _context.Add(extraData);
        await _context.SaveChangesAsync();
        return RedirectToAction("Details", new {id=extraDTO.UserId});
    }
    public async Task<IActionResult> EditExtra(int id){
        var extra = await _context.ExtraDatas.FindAsync(id);
        if(extra == null)
        {
            return NotFound();
        }
        return View(extra);
    }
    [HttpPost]
    public async Task<IActionResult> EditExtra(int id, ExtraUpdateDTO extraDTO){
        var extra = await _context.ExtraDatas.FindAsync(id);
        if(extra == null)
        {
            return NotFound();
        }
        extra.UpdateExtraData(extraDTO);
        _context.Update(extra);
        await _context.SaveChangesAsync();
        return RedirectToAction("Details", new { id=extra.UserId });
    }
    [HttpPost, ActionName("DeleteExtra")]
    public async Task<IActionResult> DeleteExtra(int id, int extraId){
        var extra = await _context.ExtraDatas.FindAsync(extraId);
        if(extra == null)
        {
            return NotFound();
        }
        _context.Remove(extra);
        await _context.SaveChangesAsync();
        return RedirectToAction("Details", new { id });
    }
}

Views/User/CreateNewUser.cshtml
@model UserNotepad.DTOs.UserDTO

@{
    ViewData["Title"] = "Create New";
}

<h1>Create New User</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewUser" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input type="date" asp-for="BirthDate" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListUsers">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/User/DeleteUser.cshtml
@model UserNotepad.Models.User
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete User</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteUser" method="post">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>:
                @Html.DisplayFor(modelItem => Model.Name)
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>:
                @Html.DisplayFor(modelItem => Model.Surname)
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>:
                @Html.DisplayFor(modelItem => Model.Gender)
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>:
                @Convert.ToString(Model.BirthDate)
            </div>
            @* Show extras  *@
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
        <a asp-action="ListUsers">Back to List</a>
</div>

Views/User/EditUser.cshtml
@model UserNotepad.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit User</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditUser" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input type="date" asp-for="BirthDate" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="btn btn-secondary">
        <a asp-action="ListUsers">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/User/ListUsers.cshtml
@model IEnumerable<UserNotepad.Models.User>
@{
    ViewData["Title"] = "User Page";
}
<h1>User List</h1>

<div>
    <a asp-action="CreateNewUser">Create New User</a>
</div>

@if(Model != null){
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Surname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BirthDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {  
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Convert.ToString(item.BirthDate)
                        @Html.Raw("<script>console.log('"+item.BirthDate+"')</script>")
                    </td>
                    <td>
                        <a asp-action="EditUser" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-controller="UserExtras" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="DeleteUser" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}